#
# weechat -- sec.conf
#
# WARNING: It is NOT recommended to edit this file by hand,
# especially if WeeChat is running.
#
# Use commands like /set or /fset to change settings in WeeChat.
#
# For more info, see: https://weechat.org/doc/weechat/quickstart/
#

[crypt]
cipher = aes256
hash_algo = sha256
passphrase_command = ""
salt = on

[data]
__passphrase__ = on
zncpass = "3A1001A26092527C77BB255E3189933CC3C29C535A1BC2C9554A7A6543F215BF7DBCA57B5E4E814716D17BBB9ACF840A145AB1DD42623ECB97C97A29D04890B9F6CC70EEEA06ECD841D406E44C588383D9394DDA409BAD078E59AD54A14129284B0E369FFE298A5C35"
