#
# weechat -- sec.conf
#
# WARNING: It is NOT recommended to edit this file by hand,
# especially if WeeChat is running.
#
# Use commands like /set or /fset to change settings in WeeChat.
#
# For more info, see: https://weechat.org/doc/weechat/quickstart/
#

[crypt]
cipher = aes256
hash_algo = sha256
passphrase_command = ""
salt = on

[data]
__passphrase__ = on
zncpass = "D1DC832EF408BBF482B4C9E0B106C5299BFD8A4E00CD749A78B79C0ABEAC779895E8FE845A9D972484AAEC4DC8ECB33C564D566A2678D6BD5BC837BCA82B28D98FC7AC7914CB7844A445F8F53C751149E3D98EF9F2E2B14947A15A480A25E8BE29FA9DCAE698254D4B"
