#
# weechat -- sec.conf
#
# WARNING: It is NOT recommended to edit this file by hand,
# especially if WeeChat is running.
#
# Use commands like /set or /fset to change settings in WeeChat.
#
# For more info, see: https://weechat.org/doc/weechat/quickstart/
#

[crypt]
cipher = aes256
hash_algo = sha256
passphrase_command = ""
salt = on

[data]
__passphrase__ = on
zncpass = "F541EF708969F20E6EB1CCEC5DDE8631B7CAF5BF34BD9FCB29E4EB45F9E1A3B6CC68CFE789A4AB5997B4389F294B541ED2DBFF19613E7102AEBD98F323E993A45027ED555C8D844A92BCDC1699BFAA75B323E70B5C234B087B937D8C0CE254502CD7B9F3E3F9F2F22C"
