[[entry]]
played_at = "2026-09-08T16:51:08Z"
path = "http://radio.cliamp.stream/lofi/stream"
title = "Lofi Stream"

[[entry]]
played_at = "2026-09-08T16:40:33Z"
path = "http://radio.cliamp.stream/edm/stream"
title = "EDM Stream"

[[entry]]
played_at = "2026-09-08T16:40:21Z"
path = "http://radio.cliamp.stream/synthwave/stream"
title = "Synthwave Stream"

[[entry]]
played_at = "2026-09-06T20:39:13Z"
path = "https://radio.cliamp.stream/ncs-dubstep/stream"
title = "NCS Dubstep"

[[entry]]
played_at = "2026-09-06T20:38:12Z"
path = "https://radio.cliamp.stream/lofi/stream"
title = "Lofi"

[[entry]]
played_at = "2026-09-06T20:37:23Z"
path = "http://stream.srg-ssr.ch/m/drs3/mp3_128"
title = "SRF 3 [128k] · Switzerland"

[[entry]]
played_at = "2026-09-06T20:30:37Z"
path = "http://radio.cliamp.stream/ncs-chill/stream"
title = "NCS Chill Stream"

[[entry]]
played_at = "2026-09-06T20:30:30Z"
path = "http://radio.cliamp.stream/ncs-trap/stream"
title = "NCS Trap Stream"

[[entry]]
played_at = "2026-09-06T20:30:24Z"
path = "http://radio.cliamp.stream/ncs-dnb/stream"
title = "NCS Drum & Bass Stream"

[[entry]]
played_at = "2026-09-06T20:30:20Z"
path = "http://radio.cliamp.stream/omarchy/stream"
title = "Omarchy Radio"

[[entry]]
played_at = "2026-09-06T20:28:48Z"
path = "http://stream.srg-ssr.ch/m/rsj/mp3_128"
title = "Radio Swiss Jazz [128k] · Switzerland"
