encryption_passcommand: sh -c 'cat "$HOME/.local/share/borgmatic/passphrase"'
source_directories:
  - /home/heavyrain
repositories:
  - path: ssh://backup-server/srv/data/Backups/darkstar-backup/Data
    label: Backup Server
    encryption: repokey-blake2
exclude_patterns:
  - "sh:**/node_modules"
  - "sh:home/*/.cache"
  - "sh:home/*/.local/share/Trash"
  - "sh:home/*/.npm"
  - "sh:home/*/.cargo/registry"
  - "sh:home/*/.cargo/git"
exclude_caches: true
exclude_if_present:
  - .nobackup

keep_weekly: 8
keep_monthly: 12
keep_yearly: 3

checks:
  - name: repository
    frequency: 1 month
  - name: archives
    frequency: 1 month
