background = 0xFF303446
base = 0xFF292C3C
alternate_base = 0xFF414559
text = 0xFFC6D0F5
bright_text = 0xFFF2D5CF
accent = 0xFFCA9EE6
accent_secondary = 0xFF8CAAEE

h1_size = 19
h2_size = 15
h3_size = 13
font_size = 11
small_font_size = 10

rounding_large = 10
rounding_small = 5
