source = $HOME/.config/hypr/frappe.conf

$monospaceFont = MonoLisa
$sansSerifFontRegular = Inter 18pt Regular
$sansSerifFontBold = Inter 18pt Bold
$barCodeFont = Libre Barcode 128 Text

# GENERAL
general {
    hide_cursor = true
    ignore_empty_input = true
    immediate_render = false
}

animations {
    enabled = true

    bezier = smooth, 0.25, 1, 0.5, 1

    animation = fadeIn,  1, 4, smooth
    animation = fadeOut, 1, 4, smooth

    animation = inputFieldColors, 1, 2, smooth
    animation = inputFieldFade,   1, 2, smooth
    animation = inputFieldWidth,  1, 2, smooth
    animation = inputFieldDots,   1, 2, smooth
}

# BACKGROUND
background {
    monitor =
    color = $base
    reload_cmd = find -L "$HOME/.config/wallpapers" -type f \( -iname '*.png' -o -iname '*.jpg' -o -iname '*.jpeg' -o -iname '*.webp' \) -print0 | shuf -z -n 1 | tr -d '\0'
    blur_size = 3
    blur_passes = 3
}


# Profie-Photo
image {
    monitor =
    path = ~/.config/avatar/cypher.png
    border_size = 2
    border_color = $crust
    size = 150
    rounding = -1
    position = 0, 250
    halign = center
    valign = center
}

# NAME
label {
    monitor =
    text = SIGINT ($USER)
    color = $text
    outline_thickness = 0
    font_size = 16
    font_family = $sansSerifFontRegular
    position = 0, 150
    halign = center
    valign = center
}

# Time
label {
    monitor =
    text = cmd[update:100] echo "$(date +'%H:%M:%S.%N')"
    color = $text
    font_size = 128
    font_family = $barCodeFont
    position = 0, 0
    halign = center
    valign = center
}

# Day-Month-Date
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%A, %d. %B %Y")"
    color = $text
    font_size = 24
    font_family = $sansSerifFontRegular
    position = 0, -150
    halign = center
    valign = center
}

# INPUT FIELD
input-field {
    monitor =
    rounding = 10
    size = 300, 50
    outline_thickness = 2
    dots_size = 0.33
    dots_spacing = 0.33
    dots_center = true
    fade_on_empty = true
    font_family = $sansSerifFontRegular

    placeholder_text = ENTER PASSPHRASE
    inner_color = $base
    font_color = $text
    outer_color = $text
    font_color = $text

    capslock_color = $yellow
    numlock_color = $yellow
    bothlock_color = $yellow

    check_color = $green
    check_text = CHECKING PASSPHRASE

    fail_color = $red
    fail_text = AUTHENTICATION FAILED

    position = 0, -250
    halign = center
    valign = center
}