[mgr]
ratio=[2,3,3]
sort_by="alphabetical"
sort_sensitive=false
sort_dir_first=false
sort_translit=false
linemode="size"
show_hidden=true
show_symlink=true
scrolloff=5

[preview]
wrap="yes"
tab_size=2
image_quality=50

[input]
cursor_blink = true